package registry

// GetCodeBuddyDomesticModels returns models supported on domestic CodeBuddy accounts (copilot.tencent.com).
func GetCodeBuddyDomesticModels() []*ModelInfo {
	now := int64(1748044800) // 2025-05-24
	return []*ModelInfo{
		{
			ID:                  "deepseek-v4.1-flash",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "DeepSeek V4.1 Flash",
			Description:         "DeepSeek V4.1 Flash via CodeBuddy",
			ContextLength:       1048576,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "deepseek-v3.2",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "DEEPSEEK V3.2",
			Description:         "DEEPSEEK V3.2 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kimi-k3",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "KIMI K3",
			Description:         "KIMI K3 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "auto",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Auto",
			Description:         "Automatic model selection via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5.3-flash",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.3 Flash",
			Description:         "GLM-5.3 Flash via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5.3",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.3",
			Description:         "GLM-5.3 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5v-turbo",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5v Turbo",
			Description:         "GLM-5v Turbo via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5.2",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.2",
			Description:         "GLM-5.2 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5.1",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.1",
			Description:         "GLM-5.1 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5.0-turbo",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.0 Turbo",
			Description:         "GLM-5.0 Turbo via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "minimax-m2.7",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "MiniMax M2.7",
			Description:         "MiniMax M2.7 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kimi-k2.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Kimi K2.5",
			Description:         "Kimi K2.5 via CodeBuddy",
			ContextLength:       256000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kimi-k2.6",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Kimi K2.6",
			Description:         "Kimi K2.6 via CodeBuddy",
			ContextLength:       256000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "hy3",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Hy3",
			Description:         "Hy3 via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "minimax-m3",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "MiniMax M3",
			Description:         "MiniMax M3 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kimi-k2.7",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Kimi K2.7 Code",
			Description:         "Kimi K2.7 Code via CodeBuddy",
			ContextLength:       256000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "hy3-preview",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Hy3 Preview",
			Description:         "Hy3 Preview via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "deepseek-v3-2-volc",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "DeepSeek V3.2 (Volc)",
			Description:         "DeepSeek V3.2 via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "deepseek-v3",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "DeepSeek V3",
			Description:         "DeepSeek V3 via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "deepseek-v4-flash",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "DeepSeek V4 Flash",
			Description:         "DeepSeek V4 Flash via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "deepseek-v4-pro",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "DeepSeek V4 Pro",
			Description:         "DeepSeek V4 Pro via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
	}
}

// GetCodeBuddyIntlModels returns all models supported on international CodeBuddy accounts (codebuddy.ai).
func GetCodeBuddyIntlModels() []*ModelInfo {
	now := int64(1748044800) // 2025-05-24
	intlModels := []*ModelInfo{
		{
			ID:                  "gpt-6-astra",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-6 Astra",
			Description:         "GPT-6 Astra via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-6-luna",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-6 Luna",
			Description:         "GPT-6 Luna via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-6",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-6",
			Description:         "GPT-6 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-5.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-5.5",
			Description:         "GPT-5.5 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-5.6-terra",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-5.6 Terra",
			Description:         "GPT-5.6 Terra via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-5.6-luna",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-5.6 Luna",
			Description:         "GPT-5.6 Luna via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-5",
			Description:         "GPT-5 via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 16384,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-4o",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-4o",
			Description:         "GPT-4o via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 16384,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-4o-mini",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT-4o Mini",
			Description:         "GPT-4o Mini via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 16384,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gpt-image-2",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "GPT Image 2",
			Description:         "GPT Image 2 via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 16384,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "codex-auto-review",
			Object:              "model",
			Created:             now,
			OwnedBy:             "openai",
			Type:                "codebuddy",
			DisplayName:         "Codex Auto Review",
			Description:         "Codex Auto Review via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 16384,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "claude-3-7-sonnet",
			Object:              "model",
			Created:             now,
			OwnedBy:             "anthropic",
			Type:                "codebuddy",
			DisplayName:         "Claude 3.7 Sonnet",
			Description:         "Claude 3.7 Sonnet via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "claude-3-7-sonnet-thinking",
			Object:              "model",
			Created:             now,
			OwnedBy:             "anthropic",
			Type:                "codebuddy",
			DisplayName:         "Claude 3.7 Sonnet (Thinking)",
			Description:         "Claude 3.7 Sonnet with Thinking via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 65536,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "claude-3-5-sonnet",
			Object:              "model",
			Created:             now,
			OwnedBy:             "anthropic",
			Type:                "codebuddy",
			DisplayName:         "Claude 3.5 Sonnet",
			Description:         "Claude 3.5 Sonnet via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gemini-2.5-pro",
			Object:              "model",
			Created:             now,
			OwnedBy:             "google",
			Type:                "codebuddy",
			DisplayName:         "Gemini 2.5 Pro",
			Description:         "Gemini 2.5 Pro via CodeBuddy",
			ContextLength:       1048576,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "gemini-2.5-flash",
			Object:              "model",
			Created:             now,
			OwnedBy:             "google",
			Type:                "codebuddy",
			DisplayName:         "Gemini 2.5 Flash",
			Description:         "Gemini 2.5 Flash via CodeBuddy",
			ContextLength:       1048576,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
	}
	return append(intlModels, GetCodeBuddyDomesticModels()...)
}

// GetCodeBuddyModels returns the superset of available models for CodeBuddy.
func GetCodeBuddyModels() []*ModelInfo {
	return GetCodeBuddyIntlModels()
}
